name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        rust: [ stable, nightly ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt
          rustup component add clippy
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libasound2-dev libxcursor-dev
      - run: cargo fmt --check
      - run: cargo clippy --workspace --examples --tests --benches
      - run: cargo build --verbose
      - run: cargo build --verbose --examples
      - run: cargo test --verbose
